steps:
  - command: "echo 'try plugin'"
    label: "Try plugin"
    plugins:
      - natasg/test#v1.0.0:
          message: 'World'

  - command: "./auto/run-unit-tests"
    label: "Run unit tests"

  - command: "./auto/check-code-style"
    label: "Check code style"

  - wait

  - command: "./auto/release"
    label: "Build and Release docker image"
    branches: "master"

  - block: "Deploy"
    branches: "master"

  - command: "./auto/deploy"
    label: "Deploy"
    branches: "master"
